/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoadingProducts: typeof import('./src/components/LoadingProducts/LoadingProducts.vue')['default']
    Product: typeof import('./src/components/ProductList/Product.vue')['default']
    ProductList: typeof import('./src/components/ProductList/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
