/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertError: typeof import('./src/components/AlertError/AlertError.vue')['default']
    CartProduct: typeof import('./src/components/CartProduct/CartProduct.vue')['default']
    Error: typeof import('./src/components/Error/Error.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    ListProduct: typeof import('./src/components/ListProduct/ListProduct.vue')['default']
    LoadingProducts: typeof import('./src/components/SkeletonProducts/LoadingProducts.vue')['default']
    Product: typeof import('./src/components/Product/Product.vue')['default']
    ProductList: typeof import('./src/components/ProductList/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonProducts: typeof import('./src/components/SkeletonProducts/SkeletonProducts.vue')['default']
  }
}
