/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {RouteRecordInfo,} from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Cart/CartPage': RouteRecordInfo<'/Cart/CartPage', '/Cart/CartPage', Record<never, never>, Record<never, never>>,
    '/Home/HomePage': RouteRecordInfo<'/Home/HomePage', '/Home/HomePage', Record<never, never>, Record<never, never>>,
    '/ProductDetails/ProductDetailsPage': RouteRecordInfo<'/ProductDetails/ProductDetailsPage', '/ProductDetails/ProductDetailsPage', Record<never, never>, Record<never, never>>,
    '/ThankYou/ThankYouPage': RouteRecordInfo<'/ThankYou/ThankYouPage', '/ThankYou/ThankYouPage', Record<never, never>, Record<never, never>>,
  }
}
